version: "3.8"
services:
  app:
    build: .
    container_name: ms-user-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ms_user
    depends_on:
      - postgres
    networks:
      - ms-user-network

  postgres:
    image: postgres:14
    container_name: ms-user-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms_user
    ports:
      - "5432:5432"
    restart: always
    networks:
      - ms-user-network

networks:
  ms-user-network:
    driver: bridge
